while True:
    a=input("請輸入金額〔輸入exit即為離開〕：")
    a=a.replace(",","",20).replace("$","",10) #有人打金額會打","
    
    if a=="exit":
        break

    try:
        int(a)
        
        if int(a)<25:
            print("吃不了喔！！")
        elif int(a)<30:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")
        elif int(a)<35:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")            
            print("塔香培根三角飯團")
            print("香酥雞堡排三角飯團")
            print("蔬菜牛蒡三角飯團")
            print("三寶素肉鬆三角飯團")
            print("什錦素總匯三角飯團")
        elif int(a)<40:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")            
            print("塔香培根三角飯團")
            print("香酥雞堡排三角飯團")
            print("蔬菜牛蒡三角飯團")
            print("三寶素肉鬆三角飯團")
            print("什錦素總匯三角飯團")            
            print("照燒豬肉三角飯團")
            print("和風燒肉三角飯團")
            print("黑胡椒肉絲三角飯團")
            print("黃金燻雞三角飯團")
            print("勁辣卡啦雞三角飯團")
            print("韓式泡菜豬肉三角飯團")
            print("鮪魚三角飯團")
            print("咖哩雞肉三角飯團")
            print("三杯雞三角飯團")
        elif int(a)<45:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")            
            print("塔香培根三角飯團")
            print("香酥雞堡排三角飯團")
            print("蔬菜牛蒡三角飯團")
            print("三寶素肉鬆三角飯團")
            print("什錦素總匯三角飯團")            
            print("照燒豬肉三角飯團")
            print("和風燒肉三角飯團")
            print("黑胡椒肉絲三角飯團")
            print("黃金燻雞三角飯團")
            print("勁辣卡啦雞三角飯團")
            print("韓式泡菜豬肉三角飯團")
            print("鮪魚三角飯團")
            print("咖哩雞肉三角飯團")
            print("三杯雞三角飯團")            
            print("韓式泡菜牛肉三角飯團")
            print("黑胡椒牛肉三角飯團")
            print("鐵板牛肉三角飯團")
        elif int(a)<50:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")            
            print("塔香培根三角飯團")
            print("香酥雞堡排三角飯團")
            print("蔬菜牛蒡三角飯團")
            print("三寶素肉鬆三角飯團")
            print("什錦素總匯三角飯團")            
            print("照燒豬肉三角飯團")
            print("和風燒肉三角飯團")
            print("黑胡椒肉絲三角飯團")
            print("黃金燻雞三角飯團")
            print("勁辣卡啦雞三角飯團")
            print("韓式泡菜豬肉三角飯團")
            print("鮪魚三角飯團")
            print("咖哩雞肉三角飯團")
            print("三杯雞三角飯團")            
            print("韓式泡菜牛肉三角飯團")
            print("黑胡椒牛肉三角飯團")
            print("鐵板牛肉三角飯團")            
            print("鹹香菜脯蛋海苔飯捲")
            print("古早味肉鬆海苔飯捲")
        elif int(a)<55:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")            
            print("塔香培根三角飯團")
            print("香酥雞堡排三角飯團")
            print("蔬菜牛蒡三角飯團")
            print("三寶素肉鬆三角飯團")
            print("什錦素總匯三角飯團")            
            print("照燒豬肉三角飯團")
            print("和風燒肉三角飯團")
            print("黑胡椒肉絲三角飯團")
            print("黃金燻雞三角飯團")
            print("勁辣卡啦雞三角飯團")
            print("韓式泡菜豬肉三角飯團")
            print("鮪魚三角飯團")
            print("咖哩雞肉三角飯團")
            print("三杯雞三角飯團")            
            print("韓式泡菜牛肉三角飯團")
            print("黑胡椒牛肉三角飯團")
            print("鐵板牛肉三角飯團")            
            print("鹹香菜脯蛋海苔飯捲")
            print("古早味肉鬆海苔飯捲")            
            print("塔香培根海苔飯捲")
            print("香酥雞堡排海苔飯捲")
            print("蔬菜牛蒡海苔飯捲")
            print("三寶素肉鬆海苔飯捲")
            print("什錦素總匯海苔飯捲")
        elif int(a)<60:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")            
            print("塔香培根三角飯團")
            print("香酥雞堡排三角飯團")
            print("蔬菜牛蒡三角飯團")
            print("三寶素肉鬆三角飯團")
            print("什錦素總匯三角飯團")            
            print("照燒豬肉三角飯團")
            print("和風燒肉三角飯團")
            print("黑胡椒肉絲三角飯團")
            print("黃金燻雞三角飯團")
            print("勁辣卡啦雞三角飯團")
            print("韓式泡菜豬肉三角飯團")
            print("鮪魚三角飯團")
            print("咖哩雞肉三角飯團")
            print("三杯雞三角飯團")            
            print("韓式泡菜牛肉三角飯團")
            print("黑胡椒牛肉三角飯團")
            print("鐵板牛肉三角飯團")            
            print("鹹香菜脯蛋海苔飯捲")
            print("古早味肉鬆海苔飯捲")            
            print("塔香培根海苔飯捲")
            print("香酥雞堡排海苔飯捲")
            print("蔬菜牛蒡海苔飯捲")
            print("三寶素肉鬆海苔飯捲")
            print("什錦素總匯海苔飯捲")            
            print("照燒豬肉海苔飯捲")
            print("和風燒肉海苔飯捲")
            print("黑胡椒肉絲海苔飯捲")
            print("黃金燻雞海苔飯捲")
            print("勁辣卡啦雞海苔飯捲")
            print("韓式泡菜豬肉海苔飯捲")
            print("鮪魚海苔飯捲")
            print("咖哩雞肉海苔飯捲")
            print("三杯雞海苔飯捲")
        elif int(a)<2000:
            print("鹹香菜脯蛋三角飯團")
            print("古早味肉鬆三角飯團")            
            print("塔香培根三角飯團")
            print("香酥雞堡排三角飯團")
            print("蔬菜牛蒡三角飯團")
            print("三寶素肉鬆三角飯團")
            print("什錦素總匯三角飯團")            
            print("照燒豬肉三角飯團")
            print("和風燒肉三角飯團")
            print("黑胡椒肉絲三角飯團")
            print("黃金燻雞三角飯團")
            print("勁辣卡啦雞三角飯團")
            print("韓式泡菜豬肉三角飯團")
            print("鮪魚三角飯團")
            print("咖哩雞肉三角飯團")
            print("三杯雞三角飯團")            
            print("韓式泡菜牛肉三角飯團")
            print("黑胡椒牛肉三角飯團")
            print("鐵板牛肉三角飯團")            
            print("鹹香菜脯蛋海苔飯捲")
            print("古早味肉鬆海苔飯捲")            
            print("塔香培根海苔飯捲")
            print("香酥雞堡排海苔飯捲")
            print("蔬菜牛蒡海苔飯捲")
            print("三寶素肉鬆海苔飯捲")
            print("什錦素總匯海苔飯捲")            
            print("照燒豬肉海苔飯捲")
            print("和風燒肉海苔飯捲")
            print("黑胡椒肉絲海苔飯捲")
            print("黃金燻雞海苔飯捲")
            print("勁辣卡啦雞海苔飯捲")
            print("韓式泡菜豬肉海苔飯捲")
            print("鮪魚海苔飯捲")
            print("咖哩雞肉海苔飯捲")
            print("三杯雞海苔飯捲")            
            print("韓式泡菜牛肉海苔飯捲")
            print("黑胡椒牛肉海苔飯捲")
            print("鐵板牛肉海苔飯捲")
        elif int(a)>2000:
            print("你幾乎都吃得起了！")
    except:
        print("這不是數字字元！")



